#+ summary: get FTU images and parts

PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ccf: <http://purl.org/ccf/>
PREFIX UBERON: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX CL: <http://purl.obolibrary.org/obo/CL_>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX HRA: <https://purl.humanatlas.io/collection/hra>

SELECT ?organ ?ftu_label ?ftu_iri ?ftu_part_label ?ftu_part_iri ?ftu_part_type (COUNT(DISTINCT ?ftu_part) as ?ftu_part_count)
# SELECT *
FROM HRA:
WHERE {
  [] a ccf:FtuIllustration ;
      ccf:ccf_located_in ?organ_iri ;
      ccf:representation_of ?ftu_iri ;
      ccf:illustration_node ?ftu_part ;
  .
  ?ftu_part a ccf:FtuIllustrationNode ;
    ccf:representation_of ?ftu_part_iri ;
  .

  BIND(IF(STRSTARTS(STR(?ftu_part_iri), STR(UBERON:)), 'AS', 'CT') as ?ftu_part_type)
  ?organ_iri rdfs:label ?organ .
  ?ftu_iri rdfs:label ?ftu_label .
  ?ftu_part_iri rdfs:label ?ftu_part_label .
}
GROUP BY ?organ ?ftu_label ?ftu_iri ?ftu_part_label ?ftu_part_iri ?ftu_part_type
ORDER BY ?organ ?ftu_label ?ftu_part_label