name: Publish staging dashboard data

on:
  push:
    branches: ['develop']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          find ./data/ \( -name '*.yaml' -o -name '*.vl.json' \) -exec sed -i 's|https://cdn\.humanatlas\.io/hra-dashboard-data/|https://cdn.humanatlas.io/hra-dashboard-data--staging/|g' {} +
          aws s3 sync --delete ./data/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}/hra-dashboard-data--staging/
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/hra-dashboard-data--staging/*"
